dist: bionic
language: java
jdk:
 - openjdk15
env:
 global:
  - secure: "0hceZKeIRJKdozePCHYYk15yDrHsBbiOvLt4aWPgxe7mR5gvNMFETA2DCdGlZumQo81fqF1qOpZOC6+sKRxFiz2yiNGsxmh+vtR3j/kRIxg5wvT1yBNFlYNGAZf4g2XurtctEpIXAMhI/T79tbtwA8y8vAPHzae+j18oecMm335D4YaEF39fnIZilNTHHscCtP4KoLra++Em/CaZMq8WNnoc3D1jBPUYRleWr3wAT0StPsfJj/Nnd/dNfs9wpQacwY0yb1qXnkbK1twTeVBlGmbWTulybMigodtcWt+h3jPCLhFPIjTZcdjBkZc5OIPPef0uyGmJjF9jA7EobnkjRNsmgiYEZaAMdL0lCUz/9pUUUk72/ubHrf+Jp5PmchcXE0ZYU0VK6dLOmcdkcBTcxS/2M6LQVSsH3XFC6uMyn5wRVMAi3hL8Hb85E2SaItYYXxD77aACvKhnJ6V1S2NRGWZebZnW4tfLK4aXLjSbTxCR5JVj4rXMx1FACmazR8nR3cl+HHA91AGGlxAZ7cl7t1xsf9i02+ZmOjsU4CUFdsD7HlBPodaemENAhuwpkPgkKEsuY5763hzvqhpRrNlUu/NoWzFSOE+TXU8UqoP3fogB6QKaC2Yw26PNTsI2g+sVmt8ZWjJIXEY3FZrunFYDUMRcEukPac7QAh3xDw7Sejk="
cache:
 directories:
  - $HOME/.m2
script:
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
 - mvn -T 1C -f releng/edu.toronto.cs.se.modelepedia.libz3java.releng/pom.xml clean install
 - mvn -T 1C -f releng/edu.toronto.cs.se.mmint.releng/pom.xml clean install
after_success:
 - >
   test $TRAVIS_PULL_REQUEST = false &&
   git clone https://github.com/amgrubb/amgrubb.github.io.git &&
   cd amgrubb.github.io &&
   rm -rf mmint/${TRAVIS_BRANCH/master/release} &&
   mv $TRAVIS_BUILD_DIR/releng/edu.toronto.cs.se.mmint.install/target/repository mmint/${TRAVIS_BRANCH/master/release} &&
   git add . &&
   git reset --soft HEAD~1 &&
   git commit --author="Alicia M. Grubb <amgrubb@smith.edu>" -m "mmint: Update builds" &&
   git push -f -q https://amgrubb:$TMVAR@github.com/amgrubb/amgrubb.github.io.git master &> /dev/null
